BugFix/SCAT-5254-commit
Crown-Commercial-Service/ccs-scale-cat-buyer-ui pull request #1227
Opened 2022-06-01 16:04 UTC by 2073810-Sonam

### JIRA link

### Change description

### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Review and publish page updated
- [ ] UI changes look good on mobile

### Developer self-QA run statement

- [ ] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

2022-06-01 17:21 UTC, BalwinderSinghCts requested changes
<<<<<<< feature/scat-5254
Resolve your conflict line 470 
src/main/features/requirements/controller/rfp-review.ts

2022-06-02 07:08 UTC, BalwinderSinghCts requested changes
Use common function for this also
@2073810-Sonam 
<img width="668" alt="image" src="https://user-images.githubusercontent.com/102786304/171572981-9f85a387-269c-4a12-83d3-29455b2c988c.png">

2022-06-02 08:30 UTC, BalwinderSinghCts approved these changes

2022-06-02 08:32 UTC, dhivya-cognizant approved these changes

2022-06-02 08:33 UTC, merged