Feature/scat 964 procurement overview
Crown-Commercial-Service/ccs-scale-cat-buyer-ui pull request #201
Opened 2021-11-02 17:51 UTC by CesarPerez

### JIRA link
https://crowncommercialservice.atlassian.net/browse/SCAT-964

### Change description

Added template to show the procurement, the first time you enter in the lot the project is created but is not fully ready yet (we manage to get the response from the post endpoint but we need to display the data on the procurement template tomorrow), 

### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Check and send page updated
- [ ] UI changes look good on mobile

### Developer self-QA run statement

- [ ] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2021-11-03 15:40 UTC, ulysses-cognizant approved these changes

2021-11-03 15:51 UTC, prathap-cognizant requested changes

2021-11-03 15:51 UTC, prathap-cognizant commented on src/main/common/middlewares/agreementservice/chooseagreement.ts
> +        let BaseURL = "/agreements/RM1043.6/lots";
We need to change it to RM6263

2021-11-03 15:51 UTC, prathap-cognizant commented on src/main/features/dashboard/controller/dashboard.ts
> +  res.cookie('agreement_id', 'RM1043.6', { maxAge: 900000, httpOnly: true });
need to change it to RM6263

2021-11-03 16:02 UTC, CesarPerez commented on src/main/common/middlewares/agreementservice/chooseagreement.ts
> +        let BaseURL = "/agreements/RM1043.6/lots";
```suggestion
        let BaseURL = "/agreements/RM6263/lots";
```

2021-11-03 16:02 UTC, CesarPerez commented on src/main/features/dashboard/controller/dashboard.ts
> +  res.cookie('agreement_id', 'RM1043.6', { maxAge: 900000, httpOnly: true });
```suggestion
  res.cookie('agreement_id', 'RM6263', { maxAge: 900000, httpOnly: true });
```

2021-11-03 16:57 UTC, prathap-cognizant requested changes
Can you add unit test cases for your code changes.

2021-11-05 11:08 UTC, prathap-cognizant approved these changes

2021-11-05 11:08 UTC, merged

2021-11-05 11:10 UTC, viswa-cognizant approved these changes
Looks Good