SCAT 1852 - Session timeout & management
Crown-Commercial-Service/ccs-scale-cat-buyer-ui pull request #202
Opened 2021-11-03 16:59 UTC by daimdev

### JIRA link

https://crowncommercialservice.atlassian.net/browse/SCAT-1852

### Change description

developed the feature/SCAT-1852 Session time out Management 

### Work checklist

- [ ] Unit tests added where applicable
- [ ] Route tests added for new pages
- [ ] New pages included in a11y tests
- [ ] Check and send page updated
- [ ] UI changes look good on mobile

### Developer self-QA run statement

- [ ] I have clicked through the running application to see if all changes I made actually work.

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

2021-11-03 17:06 UTC, prathap-cognizant requested changes
Add the unit test case for all the files releated to redis and auth functionality.

2021-11-03 17:06 UTC, prathap-cognizant commented on src/main/common/middlewares/oauthservice/authstatecheck.ts
> +                       console.log(err)
errors needs to be logged in logit

2021-11-03 17:17 UTC, ulysses-cognizant approved these changes

2021-11-04 10:59 UTC, prathap-cognizant approved these changes

2021-11-04 11:08 UTC, merged