ECS migration changes to Buyer UI
Crown-Commercial-Service/ccs-scale-cat-buyer-ui pull request #4497
Opened 2023-11-21 14:02 UTC by mcbhenwood

Changes to facilitate provision of Buyer UI in ECS Fargate. Please review by commit for clarity.

2023-11-21 14:03 UTC, mcbhenwood commented on src/main/setup/routes/setupHomeRoutes.ts
> +import isAliveRoute from '../../routes/isAlive'
`setupHomeRoutes.ts` isn't a natural home for a healthcheck route, however I noted that the existing `/health` route is mounted here and so I've followed in the footsteps of that precedent.

2023-11-21 14:04 UTC, mcbhenwood commented on src/main/routes/isAlive.ts
> +    app.get('/isAlive', (req: Request, res: Response) => res.json({isAlive: "yes"}));
A deliberately simple, instant, "is there a server process alive?" healthcheck - The existing one is too weighty and contains too many dependencies which could lead to churn in the ECS tasks

2023-11-21 14:05 UTC, mcbhenwood commented on src/main/setup/redis/client.ts
>      redisClientOpts.socket.tls = true;
Inside our VPC we do not need TLS for Redis.

2023-11-23 15:18 UTC, NToppingCCS commented
No problems with what I see here, though it's worth noting the linting appears to have a couple of issues with it which will need resolving.

I will hold off on approving until both that is resolved, and we're in a place where we're able to merge this.

2023-12-14 12:00 UTC, NToppingCCS requested changes
@mcbhenwood looks like the build is failing on this one.  Could you bring the branch up to date and resolve that?  Once that's done, happy to approve.

2023-12-14 15:09 UTC, mcbhenwood commented
> @mcbhenwood looks like the build is failing on this one. Could you bring the branch up to date and resolve that? Once that's done, happy to approve.

Apols, I missed the failure somehow - linted and green @NToppingCCS

2023-12-14 15:09 UTC, tim-s-ccs approved these changes

2023-12-14 15:31 UTC, NToppingCCS approved these changes
Good to go now :)

2023-12-14 15:36 UTC, merged